## Code summary:
The goal is to reach an accuracy of 75%. This first trial reaches 74%, so further trials have been conducted

## Preprocessing

In [136]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("https://static.bc-edx.com/data/dla-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [137]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns=['EIN', 'NAME'])
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [138]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [139]:
# Look at APPLICATION_TYPE value counts for binning
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [140]:
# Choose a cutoff value and create a list of application types to be replaced

# use the variable name `application_types_to_replace`
application_types_to_replace = application_df['APPLICATION_TYPE'].value_counts()[application_df['APPLICATION_TYPE'].value_counts() < 500].index

# # Replace in dataframe
application_df['APPLICATION_TYPE'][application_df['APPLICATION_TYPE'].isin(application_types_to_replace)] = 'Other'


# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

C:\Users\bosb0\AppData\Local\Temp\ipykernel_11340\4096795577.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  application_df['APPLICATION_TYPE'][application_df['APPLICATION_TYPE'].isin(application_types_to_replace)] = 'Other'

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [141]:
# Look at CLASSIFICATION value counts for binning
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [142]:
# You may find it helpful to look at CLASSIFICATION value counts >1
application_df['CLASSIFICATION'].value_counts()[application_df['CLASSIFICATION'].value_counts() > 1]

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [143]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = application_df['CLASSIFICATION'].value_counts()[application_df['CLASSIFICATION'].value_counts() < 700].index

# Replace in dataframe
application_df['CLASSIFICATION'][application_df['CLASSIFICATION'].isin(classifications_to_replace)] = 'Other'
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C:\Users\bosb0\AppData\Local\Temp\ipykernel_11340\2695739955.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  application_df['CLASSIFICATION'][application_df['CLASSIFICATION'].isin(classifications_to_replace)] = 'Other'

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
Other     1484
C7000      777
Name: count, dtype: int64

In [144]:
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [145]:
# Convert categorical data to numeric with `pd.get_dummies`
numerical_columns = ['STATUS', 'ASK_AMT']
dummy_columns = ['APPLICATION_TYPE', 'AFFILIATION', 'CLASSIFICATION', 'USE_CASE', 'ORGANIZATION', 'INCOME_AMT', 'SPECIAL_CONSIDERATIONS']
dummy_df = pd.get_dummies(application_df, columns=dummy_columns, dtype=int)
application_processed = pd.concat([dummy_df, application_df[numerical_columns]], axis=1)

In [146]:
# Split our preprocessed data into our features and target arrays
y = application_processed['IS_SUCCESSFUL']
X = application_processed.drop(columns='IS_SUCCESSFUL')
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [147]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

Using KerasTuner to evaluate the current top configurations-- aim of 75%

## Trial 1:

In [148]:


def create_model(hp):
    nn_model = tf.keras.models.Sequential()

    # Allow kerastuner to decide which activation function to use in hidden layers
    activation = hp.Choice('activation', ['relu', 'tanh', 'sigmoid'])
    
    # Allow kerastuner to decide number of neurons in first layer
    nn_model.add(tf.keras.layers.Dense(units=hp.Int('first_units',
                                                     min_value=1,
                                                     max_value=30,
                                                     step=5), activation=activation, input_dim=X_train_scaled.shape[1]))

    # Allow kerastuner to decide number of hidden layers and neurons in hidden layers
    for i in range(hp.Int('num_layers', 1, 5)):
        nn_model.add(tf.keras.layers.Dense(units=hp.Int('units_' + str(i),
                                                         min_value=1,
                                                         max_value=30,
                                                         step=5),
                                           activation=activation))
    
    nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

    # Compile the model
    nn_model.compile(loss="binary_crossentropy", optimizer='adam', metrics=["accuracy"])
    
    return nn_model

In [149]:
import keras_tuner as kt

tuner = kt.Hyperband(
    create_model,
    objective="val_accuracy",
    max_epochs=20,
    hyperband_iterations=2)

c:\Users\bosb0\anaconda3.1\envs\dev\lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [150]:
# Run the kerastuner search for best hyperparameters
tuner.search(X_train_scaled,y_train,epochs=20,validation_data=(X_test_scaled,y_test))

Trial 60 Complete [00h 00m 15s]
val_accuracy: 0.732478141784668

Best val_accuracy So Far: 0.7338775396347046
Total elapsed time: 00h 07m 41s

In [151]:
# Get best model hyperparameters
best_hyper = tuner.get_best_hyperparameters(1)[0]
best_hyper.values

{'activation': 'sigmoid',
 'first_units': 26,
 'num_layers': 3,
 'units_0': 16,
 'units_1': 16,
 'units_2': 16,
 'units_3': 11,
 'units_4': 6,
 'tuner/epochs': 7,
 'tuner/initial_epoch': 0,
 'tuner/bracket': 1,
 'tuner/round': 0}

In [156]:
# Define the deep learning model 
nn_model = tf.keras.models.Sequential()
nn_model.add(tf.keras.layers.Dense(units=26, activation="sigmoid", input_dim=X_train_scaled.shape[1]))
nn_model.add(tf.keras.layers.Dense(units=3, activation="sigmoid"))
nn_model.add(tf.keras.layers.Dense(units=16, activation="sigmoid"))
nn_model.add(tf.keras.layers.Dense(units=16, activation="sigmoid"))
nn_model.add(tf.keras.layers.Dense(units=16, activation="sigmoid"))
nn_model.add(tf.keras.layers.Dense(units=11, activation="sigmoid"))
nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))  # Adjust the units to 1 for binary classification

# Compile the Sequential model together and customize metrics
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

# Train the model
fit_model = nn_model.fit(X_train_scaled, y_train, epochs=100, initial_epoch=7)

# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled, y_test, verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Epoch 8/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 705us/step - accuracy: 0.5399 - loss: 0.6871
Epoch 9/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 726us/step - accuracy: 0.7303 - loss: 0.5785
Epoch 10/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 690us/step - accuracy: 0.7260 - loss: 0.5800
Epoch 11/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 684us/step - accuracy: 0.7307 - loss: 0.5726
Epoch 12/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 699us/step - accuracy: 0.7325 - loss: 0.5715
Epoch 13/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 707us/step - accuracy: 0.7288 - loss: 0.5763
Epoch 14/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 684us/step - accuracy: 0.7324 - loss: 0.5702
Epoch 15/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 683us/step - accuracy: 0.7330 - loss: 0.5729
Epoch 16/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 684us/step - accuracy: 0.7300 - loss: 0.5722
Epoch 17/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 684us/step - accuracy: 0.7325 - loss: 0.5707
Epoch 18/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 693us/step - accuracy: 0.7362 - loss: 0.5671
Epoch 19/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 709us/step - accuracy: 0.7316 - loss: 0.5714
Epoch 20/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 682us/step - accuracy: 0.7361 - loss: 0.5653
Epoch 21/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 679us/step - accuracy: 0.7356 - loss: 0.5662
Epoch 22/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 679us/step - accuracy: 0.7293 - loss: 0.5709
Epoch 23/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 701us/step - accuracy: 0.7352 - loss: 0.5642
Epoch 24/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 683us/step - accuracy: 0.7350 - loss: 0.5654
Epoch 25/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 716us/step - accuracy: 0.7320 - loss: 0.5659
Epoch 26/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 690us/step - accuracy: 0.7303 - loss: 0.5666
Epoch 27/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 689us/step - accuracy: 0.7331 - loss: 0.5652
Epoch 28/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 683us/step - accuracy: 0.7368 - loss: 0.5609
Epoch 29/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 682us/step - accuracy: 0.7370 - loss: 0.5621
Epoch 30/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 688us/step - accuracy: 0.7364 - loss: 0.5594
Epoch 31/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 707us/step - accuracy: 0.7404 - loss: 0.5530
Epoch 32/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 711us/step - accuracy: 0.7381 - loss: 0.5567
Epoch 33/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 689us/step - accuracy: 0.7342 - loss: 0.5583
Epoch 34/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 686us/step - accuracy: 0.7358 - loss: 0.5564
Epoch 35/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 681us/step - accuracy: 0.7349 - loss: 0.5571
Epoch 36/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 668us/step - accuracy: 0.7302 - loss: 0.5626
Epoch 37/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 682us/step - accuracy: 0.7351 - loss: 0.5555
Epoch 38/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 715us/step - accuracy: 0.7384 - loss: 0.5533
Epoch 39/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 715us/step - accuracy: 0.7353 - loss: 0.5551
Epoch 40/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 732us/step - accuracy: 0.7331 - loss: 0.5584
Epoch 41/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 714us/step - accuracy: 0.7368 - loss: 0.5553
Epoch 42/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 703us/step - accuracy: 0.7327 - loss: 0.5585
Epoch 43/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 700us/step - accuracy: 0.7324 - loss: 0.5510
Epoch 44/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 730us/step - accuracy: 0.7285 - loss: 0.5536
Epoch 45/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 688us/step - accuracy: 0.7334 - loss: 0.5468
Epoch 46/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 701us/step - accuracy: 0.7285 - loss: 0.5528
Epoch 47/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 695us/step - accuracy: 0.7345 - loss: 0.5438
Epoch 48/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 696us/step - accuracy: 0.7361 - loss: 0.5429
Epoch 49/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 712us/step - accuracy: 0.7432 - loss: 0.5363
Epoch 50/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 707us/step - accuracy: 0.7353 - loss: 0.5477
Epoch 51/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 694us/step - accuracy: 0.7386 - loss: 0.5439
Epoch 52/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 681us/step - accuracy: 0.7314 - loss: 0.5493
Epoch 53/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 701us/step - accuracy: 0.7360 - loss: 0.5450
Epoch 54/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 710us/step - accuracy: 0.7332 - loss: 0.5478
Epoch 55/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 703us/step - accuracy: 0.7341 - loss: 0.5430
Epoch 56/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 708us/step - accuracy: 0.7376 - loss: 0.5411
Epoch 57/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 684us/step - accuracy: 0.7354 - loss: 0.5423
Epoch 58/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 687us/step - accuracy: 0.7383 - loss: 0.5406
Epoch 59/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 685us/step - accuracy: 0.7362 - loss: 0.5420
Epoch 60/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 688us/step - accuracy: 0.7373 - loss: 0.5424
Epoch 61/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 710us/step - accuracy: 0.7359 - loss: 0.5418
Epoch 62/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 680us/step - accuracy: 0.7357 - loss: 0.5424
Epoch 63/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 687us/step - accuracy: 0.7308 - loss: 0.5467
Epoch 64/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 684us/step - accuracy: 0.7362 - loss: 0.5395
Epoch 65/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 707us/step - accuracy: 0.7345 - loss: 0.5436
Epoch 66/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 685us/step - accuracy: 0.7275 - loss: 0.5469
Epoch 67/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 717us/step - accuracy: 0.7331 - loss: 0.5455
Epoch 68/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 696us/step - accuracy: 0.7317 - loss: 0.5478
Epoch 69/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 684us/step - accuracy: 0.7385 - loss: 0.5400
Epoch 70/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 688us/step - accuracy: 0.7372 - loss: 0.5426
Epoch 71/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 696us/step - accuracy: 0.7359 - loss: 0.5432
Epoch 72/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 713us/step - accuracy: 0.7347 - loss: 0.5411
Epoch 73/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 731us/step - accuracy: 0.7405 - loss: 0.5373
Epoch 74/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 715us/step - accuracy: 0.7364 - loss: 0.5414
Epoch 75/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 728us/step - accuracy: 0.7323 - loss: 0.5420
Epoch 76/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 708us/step - accuracy: 0.7286 - loss: 0.5475
Epoch 77/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 701us/step - accuracy: 0.7357 - loss: 0.5392
Epoch 78/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 730us/step - accuracy: 0.7364 - loss: 0.5407
Epoch 79/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 715us/step - accuracy: 0.7409 - loss: 0.5360
Epoch 80/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 711us/step - accuracy: 0.7334 - loss: 0.5439
Epoch 81/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 691us/step - accuracy: 0.7366 - loss: 0.5381
Epoch 82/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 709us/step - accuracy: 0.7419 - loss: 0.5315
Epoch 83/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 721us/step - accuracy: 0.7346 - loss: 0.5404
Epoch 84/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 738us/step - accuracy: 0.7382 - loss: 0.5386
Epoch 85/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 707us/step - accuracy: 0.7355 - loss: 0.5412
Epoch 86/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 713us/step - accuracy: 0.7387 - loss: 0.5378
Epoch 87/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 702us/step - accuracy: 0.7425 - loss: 0.5362
Epoch 88/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 718us/step - accuracy: 0.7348 - loss: 0.5396
Epoch 89/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 724us/step - accuracy: 0.7319 - loss: 0.5456
Epoch 90/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 707us/step - accuracy: 0.7416 - loss: 0.5369
Epoch 91/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 728us/step - accuracy: 0.7334 - loss: 0.5434
Epoch 92/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 717us/step - accuracy: 0.7369 - loss: 0.5375
Epoch 93/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 711us/step - accuracy: 0.7343 - loss: 0.5434
Epoch 94/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 750us/step - accuracy: 0.7371 - loss: 0.5405
Epoch 95/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 717us/step - accuracy: 0.7327 - loss: 0.5430
Epoch 96/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 710us/step - accuracy: 0.7427 - loss: 0.5318
Epoch 97/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 712us/step - accuracy: 0.7341 - loss: 0.5395
Epoch 98/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 711us/step - accuracy: 0.7371 - loss: 0.5399
Epoch 99/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 727us/step - accuracy: 0.7372 - loss: 0.5411
Epoch 100/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 689us/step - accuracy: 0.7365 - loss: 0.5397
268/268 - 0s - 844us/step - accuracy: 0.7298 - loss: 0.5525
Loss: 0.5524781346321106, Accuracy: 0.7297959327697754

After running the optimal conditions for additional epochs, the accuracy of the model reached 74%, which is lower than the target of 75%. At this point, manipulation of the data must be considered to heighten the results